name: simple_state
description: >-
  SimpleState is a library that makes it easy to connect your application's reactive data to the user interface.
version: 1.0.0
homepage: https://github.com/bronjham-code/simple_state

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
